= Contributing to R2DBC

First off, thank you for taking the time to contribute! 👍 🎉

== Table of Contents

* <<code-of-conduct,Code of Conduct>>
* <<how-to-contribute,How to Contribute>>
** <<discuss,Discuss>>
** <<ticket-lifecycle,Ticket Lifecycle>>
** <<submit-a-pull-request,Submit a Pull Request>>
* <<source-code-style,Source Code Style>>

[[code-of-conduct]]
== Code of Conduct

This project is governed by the link:https://github.com/pgjdbc/r2dbc-postgresql/blob/main/.github/CODE_OF_CONDUCT.adoc[Code of Conduct].
By participating you are expected to uphold this code.
Please report unacceptable behavior to r2dbc@googlegroups.com.

[[how-to-contribute]]
== How to Contribute

[[discuss]]
=== Discuss

If you have a question, check https://stackoverflow.com/tags/r2dbc[StackOverflow] using the https://stackoverflow.com/tags/r2dbc[r2dbc] tag or the link:https://groups.google.com/forum/#!forum/r2dbc[mailing list]
Find an existing discussion or start a new one if necessary.

If you suspect an issue, perform a search in the GitHub tracker of the R2DBC project, using a few different keywords.
When you find related issues and discussions, prior or current, it helps you to learn and it helps us to make a decision.

=== Create a Ticket

Reporting an issue or making a feature request is a great way to contribute.
Your feedback and the conversations that result from it provide a continuous flow of ideas.

Before you create a ticket, please take the time to <<discuss,research first>>.

If creating a ticket after a discussion on StackOverflow or the Mailing List, please provide a self-sufficient description in the ticket.
We understand this is extra work but the issue tracker is an important place of record for design discussions and decisions that can often be referenced long after the fix version, for example to revisit decisions, to understand the origin of a feature, and so on.

When ready create a ticket in GitHub.

[[ticket-lifecycle]]
=== Ticket Lifecycle

When an issue is first created, it may not be assigned and will not have a fix version.
Within a day or two, the issue is assigned to a specific committer.
The committer will then review the issue, ask for further information if needed, and based on the findings, the issue is either assigned a fix
version or rejected.

When a fix is ready, the issue is marked "Resolved" and may still be re-opened.
Once the fix is released, you will need to create a new, related ticket with a fresh description, if necessary.

[[submit-a-pull-request]]
=== Submit a Pull Request

You can contribute a source code change by submitting a pull request.

1. For all but the most trivial of contributions, please <<create-a-ticket,create a ticket>>.
The purpose of the ticket is to understand and discuss the underlying issue or feature.
We use the JIRA issue tracker as the preferred place of record for conversations and conclusions.
In that sense discussions directly under a PR are more implementation detail oriented and transient in nature.

2. Always check out the `main` branch and submit pull requests against it.
Backports to prior versions will be considered on a case-by-case basis and reflected as the fix version in the issue tracker.

3. Use short branch names, preferably based on the GitHub issue (e.g. `gh-1234`), or otherwise using succinct, lower-case, dash (-) delimited names, such as `fix-warnings`.

4. Choose the granularity of your commits consciously and squash commits that represent multiple edits or corrections of the same logical change.
See https://git-scm.com/book/en/Git-Tools-Rewriting-History[Rewriting History section of Pro Git] for an overview of streamlining commit history.

5. Format commit messages using 55 characters for the subject line, 72 lines for the description, followed by related issues, e.g. `[resolves #1234]`
See the https://git-scm.com/book/en/Distributed-Git-Contributing-to-a-Project#Commit-Guidelines[Commit Guidelines section of Pro Git] for best practices around commit messages and use `git log` to see some examples.

6. List the GitHub issue number in the PR description.

If accepted, your contribution may be heavily modified as needed prior to merging.
You will likely retain author attribution for your Git commits granted that the bulk of your changes remain intact.
You may also be asked to rework the submission.

If asked to make corrections, simply push the changes against the same branch, and your pull request will be updated.
In other words, you do not need to create a new pull request when asked to make changes.


[[source-code-style]]
== Source Code Style

We provide an IntelliJ link:https://github.com/pgjdbc/r2dbc-postgresql/blob/main/intellij-style.xml[IDEA code formatting configuration] that defines the source file coding standards.
Import and use the provided configuration to avoid formatting changes in pull requests.
